name: CI

on:
  push:
      branches:
      - master
      - develop
  pull_request:

jobs:
  check:

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x]  # [^8.12, 10.x, 12.x, 13.x]
        platform:
          # - ubuntu-latest
          # - macos-latest
          - windows-latest
        exclude:
        - node-version: ^8.12
          platform: macos-latest
        - node-version: 10.x
          platform: macos-latest
        - node-version: 12.x
          platform: macos-latest
    
    runs-on: ${{matrix.platform}}

    steps:
    - name: check out
      uses: actions/checkout@v1
    - name: set up node ${{matrix.node-version}}@${{matrix.platform}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}
    - name: install
      run: |
        node --version
        npm install
      shell: bash
      env:
        CI: true
    - name: lint & test
      run: |
        node --version
        npm test -- -f ast2xmi
      shell: bash
      env:
        CI: true